### ISSUE TITLE
console.log remaining?

### ISSUE THREAD

**Issue by wlundgren** [tomitrescak/meteor-tomi-upload-server#10]
Dear Tomi

I think that on version 1.2.4 you might have forgotten to delete some console.output call.
After upgrading, whenever I use the package functionality, the server console ouputs the path/url of images uploaded as well as their names.
It is a very minor issue, but I just wanted to let you know.

Thanks for your work.

**Comment by tomitrescak** [comment]
I'll check it ASAP

**Comment by tomitrescak** [comment]
OK. It is solved in the next release 1.2.5.
