### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by rudygunawan** [tomitrescak/meteor-tomi-upload-server#11]
I noticed that after adding this package, my meteor projects always have "Access Denied" in these 2 scenarios : 
- If I leave the package for sometime in the page that contains a file upload, 
- and if meteor do a hot code reload.

After I tried removing the package, the error gone.

**Comment by tomitrescak** [comment]
That makes no sense to me :/ 
The package has no routing information apart from the server route that does not affect either iron/flow router. Must be something in your configuration :/

**Comment by tomitrescak** [comment]
I close this as I have no response. Please reopen if necessary.
