### ISSUE TITLE
Not working on note 8 with android 4.4.2

### ISSUE THREAD

**Issue by binarytracer** [tomitrescak/meteor-tomi-upload-server#16]
hi tomi, we test our app on the galaxy note 8 with 4.4.2 android only, it seems the browse button when clicked is not opening any file explorer/manager, but lower than 4.4 works pretty well.

thanks for the package though :+1:

**Comment by binarytracer** [comment]
basically we have a meteor project build on android, install the app with apk file ( mobile app) it does not work. while using the package using android browsers ( stack or non-stack) works.

**Comment by katopz** [comment]
I think it's not server related? 
may be better move to https://github.com/tomitrescak/meteor-uploads/issues

**Comment by binarytracer** [comment]
IMO, im thinking this is somewhat related to cordova ( bootstrap stuff ). and i agree this is not related to server or serverside code.

**Comment by binarytracer** [comment]
wow.. hope im wrong. its due to android os kitkat 4.4 ( input type='file' ) is screwed!
