### ISSUE TITLE
When trying to add imageVersions getting an error that is not defined

### ISSUE THREAD

**Issue by akash6190** [tomitrescak/meteor-tomi-upload-server#17]
Hey I am trying to add imageVersions but I am getting 'that' is undefined error.

Error log as followed:
W20150904-03:00:01.837(5.5)? (STDERR)
W20150904-03:00:01.853(5.5)? (STDERR) <project_path>.meteor/local/build/programs/server/packages/tomi_upload-server.js:325
W20150904-03:00:01.861(5.5)? (STDERR)           options.uploadDir + '/' + version + '/' + that.name
W20150904-03:00:01.861(5.5)? (STDERR)                                                     ^
W20150904-03:00:01.886(5.5)? (STDERR) ReferenceError: that is not defined
W20150904-03:00:01.886(5.5)? (STDERR)     at packages/tomi:upload-server/upload_server.js:305:1
W20150904-03:00:01.886(5.5)? (STDERR)     at Array.forEach (native)
W20150904-03:00:01.887(5.5)? (STDERR)     at [object Object].FileInfo.initUrls (packages/tomi:upload-server/upload_server.js:303:1)
W20150904-03:00:01.887(5.5)? (STDERR)     at packages/tomi:upload-server/upload_server.js:332:1
W20150904-03:00:01.888(5.5)? (STDERR)     at Array.forEach (native)
W20150904-03:00:01.888(5.5)? (STDERR)     at IncomingForm.finish (packages/tomi:upload-server/upload_server.js:331:1)
W20150904-03:00:01.889(5.5)? (STDERR)     at IncomingForm.emit (events.js:92:17)
W20150904-03:00:01.889(5.5)? (STDERR)     at IncomingForm._maybeEnd (<project_path>/.meteor/packages/tomi_upload-server/.1.2.9.7j22i6++os+web.browser+web.cordova/npm/node_modules/formidable/lib/incoming_form.js:551:8)

**Comment by tomitrescak** [comment]
Fixed in #c84bb4dee1f3837209ff55a4721b0159b0232a30

Thanks for reporting!
