### ISSUE TITLE
multiple imageversions: one of them randomly fails

### ISSUE THREAD

**Issue by s7dhansh** [tomitrescak/meteor-tomi-upload-server#24]
There is no log, no exception, no error at all, but one of the versions is not created.

Can it be an imagemagick bug?

Edit: i will try gm and update

**Comment by s7dhansh** [comment]
Dug deeper:
The issue was because my tmp and upload directories were on different partitions.
The last imageversion succeeded, but others failed (mostly! and that was the point that baffled me).

Found out that you use either rename or copy+delete. But copy+delete (done when partitions are different) is asynch and your are treating it as sync.

I have attached the PR, in case you want it, but kindly fix it please.

**Comment by s7dhansh** [comment]
Thank you for accepting the PR.
Kindly bump up the version in atmosphere :)

**Comment by s7dhansh** [comment]
The package.js has been updated but atmosphere version is still 1.3.3. Can you please upload it to atmosphere?

**Comment by tomitrescak** [comment]
I hope this is solved. It's 1.3.4 now.

**Comment by s7dhansh** [comment]
yes thank you
