### ISSUE TITLE
Meteor 1.4 (node) sys is deprecated

### ISSUE THREAD

**Issue by meteorza** [tomitrescak/meteor-tomi-upload-server#36]
Hi 

Upgraded to Meteor 1.4, and received the following STDERR:

`(STDERR) (node) sys is deprecated. Use util instead.`

Thank you.

**Comment by promentol** [comment]
I am also receiving
(node) Buffer.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

And server is restarted.

**Comment by msj121** [comment]
@meteorza I think I have a fix to your issue, do you mind trying the new version of the code and updating? I don't have a live example to test on right this second. Thanks.

**Comment by msj121** [comment]
@promentol Not sure if this fix will work for your issue. If it does, please let me know; otherwise, please make a new issue. Thanks.
